services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
